import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

const neutral = {
    light: {
        primary: "#d97757",
        primaryHover: "#c66343",
        primaryText: "#fffaf5",
        menuBg: "#f1eee8",
        menuText: "#141413",
        selectActiveBg: "#f1eee8",
        selectSelectedBg: "transparent",
        selectText: "#141413",
        selectBorder: "#b0aea5",
        selectOutline: "rgba(217, 119, 87, 0.22)",
        selectShadow: "0 8px 24px rgba(20, 20, 19, 0.1), 0 2px 6px rgba(20, 20, 19, 0.04)",
        tableSelectedBg: "rgba(217, 119, 87, 0.08)",
        tableSelectedHoverBg: "rgba(217, 119, 87, 0.12)",
        layoutBg: "#faf9f5",
        containerBg: "#ffffff",
        border: "#e8e6dc",
        text: "#141413",
        textSecondary: "#6b6963",
    },
    dark: {
        primary: "#e18b6d",
        primaryHover: "#eca184",
        primaryText: "#fffaf5",
        menuBg: "#383733",
        menuText: "#fafafa",
        selectActiveBg: "#383733",
        selectSelectedBg: "transparent",
        selectText: "#fafafa",
        selectBorder: "#66645e",
        selectOutline: "rgba(225, 139, 109, 0.28)",
        selectShadow: "0 12px 28px rgba(0, 0, 0, 0.28), 0 2px 8px rgba(0, 0, 0, 0.18)",
        tableSelectedBg: "rgba(225, 139, 109, 0.12)",
        tableSelectedHoverBg: "rgba(225, 139, 109, 0.18)",
        layoutBg: "#141413",
        containerBg: "#1d1d1b",
        border: "#383733",
        text: "#faf9f5",
        textSecondary: "#b0aea5",
    },
};

export function getAntThemeConfig(dark: boolean): ThemeConfig {
    const color = dark ? neutral.dark : neutral.light;

    return {
        algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        cssVar: { key: dark ? "vozeb-pro-dark" : "vozeb-pro-light" },
        token: {
            colorPrimary: color.primary,
            colorInfo: color.primary,
            colorLink: color.primary,
            colorLinkHover: color.primaryHover,
            colorLinkActive: color.primary,
            colorTextLightSolid: color.primaryText,
            colorBgLayout: color.layoutBg,
            colorBgContainer: color.containerBg,
            colorBorder: color.border,
            colorText: color.text,
            colorTextSecondary: color.textSecondary,
            borderRadius: 8,
        },
        components: {
            Button: {
                primaryShadow: "none",
            },
            Menu: {
                itemActiveBg: color.menuBg,
                itemHoverBg: color.menuBg,
                itemSelectedBg: color.menuBg,
                itemSelectedColor: color.menuText,
                darkItemHoverBg: neutral.dark.menuBg,
                darkItemSelectedBg: neutral.dark.menuBg,
                darkItemSelectedColor: neutral.dark.menuText,
            },
            Select: {
                activeBorderColor: color.selectBorder,
                activeOutlineColor: color.selectOutline,
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgActiveHover: color.selectSelectedBg,
                hoverBorderColor: color.selectBorder,
                optionActiveBg: color.selectActiveBg,
                optionHeight: 32,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            Cascader: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgHover: color.selectActiveBg,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            TreeSelect: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                nodeHoverBg: color.selectActiveBg,
                nodeHoverColor: color.selectText,
                nodeSelectedBg: color.selectSelectedBg,
                nodeSelectedColor: color.selectText,
            },
            Table: {
                rowSelectedBg: color.tableSelectedBg,
                rowSelectedHoverBg: color.tableSelectedHoverBg,
            },
        },
    };
}
